# 日志配置
logging:
  level:
    com.detection.mapper: debug


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 180

#mysql数据库配置
spring:
   datasource:
     username: admin
     password: admin123
     url: jdbc:mysql://localhost:3306/detection?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     druid:
       #下面这两个配置，可以在每次连接的时候判断一些连接是否有效
       test-on-borrow: true
       test-while-idle: true




# MyBatis-plus配置
mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstu567yz123
  # 令牌有效期（默认30分钟）
  expireTime: 30

#数据库备份参数配置
DB:
  #需要备份的数据库IP
  COME_IP: localhost
  #还原数据库的IP
  GO_IP: localhost
  #用户名
  USER_KEY: root
  #密码
  USER_VALUE: 123
  #需要备份的数据库名
  DATA_BASE: detection
